### ISSUE TITLE
[Feature request] Support setting/getting colors from widgets in AppBar

### ISSUE THREAD

**Issue by adamkoch** [hm21/pro_image_editor#105]
### Platforms

Android, iOS, Web

### Description

It's possible to customize the color widget already (https://github.com/hm21/pro_image_editor/issues/70), but I'm wondering if there's a way to support setting and getting the current foreground and background colors for use in the AppBar widgets (like an icon for example).

Unlike the other text styles, it doesn't seem to work if getting and setting the text style from the AppBar.

### Why

I'm trying to include all editing features in the top AppBar vs using buttons on the editor area or at the bottom bar.

**Comment by hm21** [comment]
I'm not sure if I understand you correctly, but you just want to change the color as an example to red, right? If so, you can do it in “configs/imageEditorTheme/nameFromEditor/appBarBackgroundColor”. A full example of how to change the theme can you checkout [here](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/design_examples/highly_configurable_example.dart).

I also released now version `4.0.0` which brings you more custom widgets which also allow you to directly access the current editor state in case you need to get/set something there.

**Comment by adamkoch** [comment]
@hm21 - sorry I didn't explain very well.

This is what I currently have:

https://github.com/hm21/pro_image_editor/assets/869261/09f47cf5-4347-4edf-a0ce-262d4e1d7645




What I would like to do is move the color selector I have into the AppBar and also add another color selector for the background color as well.

I tried before and the AppBar was unable to get the current color state. I'll try it with `4.0.x` versions and see if I can get it working with the new system.

**Comment by adamkoch** [comment]
Not sure if I'm doing this right, but I tried using the new system and it doesn't seem to work:
```
StreamBuilder(
  stream: updateStream,
  builder: (context, snapshot) {
    return IconButton(
      icon: Icon(Icons.color_lens_outlined,
          color: textEditor.selectedTextStyle.color),
      onPressed: () {
        textEditor.setTextStyle(
          textEditor.selectedTextStyle.copyWith(
            color: Colors.red,
          ),
        );
      },
    );
  },
),   
```

Where I pass through `textEditor` and `updateStream` from `ReactiveCustomAppbar`. Although I guess I shouldn't need to use a `StreamBuilder` now as that's what `ReactiveCustomAppbar` does?

Even so, the `textEditor.selectedTextStyle.color` does not seem to be reactive where as bold/underline does seem to be.

**Comment by adamkoch** [comment]
@hm21 just tagging you in case you missed this as it's a closed issue

**Comment by hm21** [comment]
Ah, my bad, I already closed this topic. I'm not sure what I set in the settings, but you can also reopen the issue, right? I will reopen the issue now, but feel free to reopen it by yourself if your issue/future request is not resolved ;)

Anyway, I will take a closer look at your posts later when I find the time and answer you then.

**Comment by adamkoch** [comment]
No probs. I don't think I had permission to re-open :)

**Comment by hm21** [comment]
Ah, I got it. The main problem is that you update the color from the text style. The problem is because the user can change the background mode where the color can also be used as background color and not text color, we cannot set it that way. In the texteditor you will find the parameter `primaryColor` which will handle the color from the text or background depending on the background mode. 

Anyway, you can call now `colorChanged` to change the color, which should fix it.

Your code with the streambuilder should still work when you call `colorChanged`. However, I recommend you to use the new way, which is a bit easier, and you don't need to wrap every icon in the appbar with the streambuilder anymore.

```dart
 customWidgets: ImageEditorCustomWidgets(
    textEditor: CustomWidgetsTextEditor(
      appBar: (textEditor, rebuildStream) {
        return ReactiveCustomAppbar(
          stream: rebuildStream,
          builder: (context) {
            return AppBar(
              title: const Text('Test'),
              actions: [
                IconButton(
                  icon: Icon(Icons.color_lens_outlined,
                      color: textEditor.selectedTextStyle.color),
                  onPressed: () {
                    textEditor.colorChanged(Colors.red);
                  },
                ),
                /// Other buttons...
              ],
            );
          },
        );
      },
    ),
  )
```

Please let me know if it didn't work by you.

**Comment by adamkoch** [comment]
Ahh thanks, yes what I was after was, I needed to use `textEditor.primaryColor` to fetch the color and `textEditor.colorChanged()` to set the color.

Would it be possible to have matching calls for the background color as well? 
 - `textEditor.backgroundColor`
 - `textEditor.backgroundColorChanged()`

**Comment by hm21** [comment]
The problem is, by default you have multiple background modes, which means the primary color can be the text color or text background depending on the mode. If I add an option that sets the secondaryColor, it will destroy the background mode function because now it calculates the secondary color like below:

```dart
Color getContrastColor(Color color) {
  int d = color.computeLuminance() > 0.5 ? 0 : 255;
  
  return Color.fromARGB(color.alpha, d, d, d);
}
```
Anyway, in case you don't need multiple background modes and just want to set the color for foreground and background by yourself, you can now do it like below in version `4.0.4`. Keep in mind that after you set a secondary color by yourself, it will always be used and not automatically calculated from the primary color.

```dart
///  It's no longer necessary to call `colorChanged`.
textEditor.primaryColor = color;
textEditor.secondaryColor = color;
```

**Comment by adamkoch** [comment]
Thanks! That works perfectly. Yes I plan to allow background color selection directly and also an opacity selector as well instead of the built-in background modes.

**Comment by adamkoch** [comment]
There seems to be one more minor bug/issue with this. `secondaryColor` can be set and takes effect in the layer. But when coming back into the text editor, it seems to reset itself to the default color again.

A bit hard to explain, here is a video. I set the background color to blue, which works fine, but when I come back in, the `secondaryColor` is set back to white again. 

https://github.com/hm21/pro_image_editor/assets/869261/1a9ca7db-6630-4a8b-81b0-444de100ab37

**Comment by hm21** [comment]
Should also be fixed in version `4.0.5`, but please let me know if this issue still exists by you.

**Comment by adamkoch** [comment]
Thanks, fixed!!
