### ISSUE TITLE
when i click on blur and filter buttons my previous changes were disappear and when i complete the operation the changes were reappear again

### ISSUE THREAD

**Issue by Mohammad2464** [hm21/pro_image_editor#27]
**Describe the bug**

**Steps to Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by hm21** [comment]
Thank you for reporting a problem. Unfortunately, I can't reproduce your problem. Can you please give me some more details on how I can reproduce it?

- Are you already using the latest version `2.6.6`?
- On which platform do you have this issue (iOS, Android, Windows...) or does it happen on every platform?
- The blur editor has no buttons, so you mean only the filter options, or you mean when you first set the blur factor in the blur editor and then when you choose a filter it removes everything?

For your information, the filter editor works like this: you select a filter, confirm it and then select another one if necessary, but you can't apply multiple filters directly (but it should be possible to create your own solution for this case).

**Comment by Mohammad2464** [comment]
Basically the blur and filter options worked fine but for example if I use
text function first and I write text it will looks fine on image but when I
choose blur or filter function the text were disappear and after when I
completed blur function it reappear again that's the issue other functions
working fine only these two functions were created issue for me and I am
using Android real device for testing

**Comment by Mohammad2464** [comment]
Sorry I just checked know my issue were solved when I updated the version
of package only the issue I found know when I crop image it takes some time

**Comment by hm21** [comment]
Yeah, the crop-rotate editor is not good because this editor depends on other packages like `extended_image` that make it slow. In production builds of android, it is better and does not feel as slow as when we are debugging, but still not perfect. 

Anyway, as you can see in [this issue](https://github.com/hm21/pro_image_editor/issues/23#issuecomment-2044519142) and this [project roadmap](https://github.com/users/hm21/projects/5/views/1?filterQuery=) I started to replace it with my own better and faster solution which also animates rotation, allows flipping the image, supports double tap and more. But creating a complete own solution will take a lot of time, so I can't say when I will release it. If you want to help write code or just test what the new editor looks like, you can open the `dev-branch', but remember that it's still a work in progress, so many things are still buggy.

**Comment by Mohammad2464** [comment]
So for crop I can use custom widget? And one more issue is that close
editor show me black screen

**Comment by hm21** [comment]
What do you mean by custom widget in crop? 

The black screen is usually a sign that the user is calling Navigator.pop(context) too many times. Can you show me the code of your ProImageEditor widget so that I can take a look at it where the problem is.

**Comment by Mohammad2464** [comment]
// ignore_for_file: use_super_parameters,
prefer_typing_uninitialized_variables, prefer_const_constructors

import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get_state_manager/src/rx_flutter/rx_obx_widget.dart';
import 'package:image_picker/image_picker.dart';
import 'package:photo_editing/home_controller.dart';
import 'package:photo_editing/widgets/button.dart';
import 'package:photo_editing/widgets/stickers.dart';
import 'package:pro_image_editor/pro_image_editor_main.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final controller = Homecontroller();
  var editedimage;

  bool isImageSelected = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(
          "Photo App",
          style: TextStyle(color: Colors.white),
        ),
        centerTitle: true,
        backgroundColor: Colors.blue, // Change app bar background color
      ),
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          if (!isImageSelected)
            Container(
              color: Colors.grey[200],
              padding: EdgeInsets.symmetric(vertical: 20, horizontal: 16),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  PhotoButton(
                    text: "Take Image",
                    onPressed: () {
                      controller.pickImage(ImageSource.camera);
                      setState(() {
                        isImageSelected = true;
                      });
                    },
                    icon: Icons.camera,
                    color: Colors.blue, // Set button background color
                  ),
                  SizedBox(width: 10),
                  PhotoButton(
                    text: "Select from Gallery",
                    onPressed: () {
                      controller.pickImage(ImageSource.gallery);
                      setState(() {
                        isImageSelected = true;
                      });
                    },
                    icon: Icons.collections,
                    color: Colors.green, // Set button background color
                  ),
                ],
              ),
            ),
          Expanded(
            child: Obx(
              () {
                return controller.imageFile.value.path.isEmpty
                    ? Center(child: Text("No image selected"))
                    : ProImageEditor.file(
                        File(controller.imageFile.value.path),
                        onImageEditingComplete: (editedImage) async {
                          controller.saveImage(context, editedImage);
                          setState(() {
                            isImageSelected = false;
                          });
                        },
                        configs: stickers(),


                      );
              },
            ),
          ),
        ],
      ),
    );
  }
}

**Comment by hm21** [comment]
Got it, you don't want to close the editor when the user is done editing. You can add the `allowCompleteWithEmptyEditing' parameter which should fix this.

As an example: 
```dart
ProImageEditor.file(
      File(controller.imageFile.value.path),
      allowCompleteWithEmptyEditing: true,
      onImageEditingComplete: (editedImage) async {
        controller.saveImage(context, editedImage);
        setState(() {
          isImageSelected = false;
        });
      },
      configs: stickers(),
 );
```

**Comment by Mohammad2464** [comment]
Ok thanks but what should happen when I press on close editor button
according to my scenerio

**Comment by hm21** [comment]
In your scenario, I think you might display the result without showing it in the editor, so it will look something like this:

```dart
return controller.imageFile.value.path.isEmpty
        ? Center(child: Text("No image selected"))
        : resultBytes != null
            ? Image.memory(
                resultBytes,
                fit: BoxFit.contain,
              )
            : ProImageEditor.file(
                File(controller.imageFile.value.path),
                onImageEditingComplete: (editedImage) async {
                  controller.saveImage(context, editedImage);
                  resultBytes = editedImage;
                  setState(() {
                    isImageSelected = false;
                  });
                },
                configs: stickers(),
              );
```

**Comment by Mohammad2464** [comment]
Hi I can found one more issue in your package. In app bar both of buttons
on close editor and on editing done buttons provide same functionality even
I just added to show me alert dialog when user done no changes before
closing editor but it was also showing me on editing button

**Comment by hm21** [comment]
Hi, what you are mentioning are the two callbacks `onCloseEditor` and `onImageEditingComplete` and not “buttons” right?
These two callbacks can be triggered at the same time or not depending on the way you use the editor in the callback `onImageEditingComplete`. You can run your own code like upload to a server or something else which still show the same loading alert like from the process to capture an image. The full code you can check out [here](https://github.com/hm21/pro_image_editor/blob/0ccac734079363964f6f3bde3956bc960e01466f/lib/modules/main_editor/main_editor.dart#L1286), but in short the code looks like this: 

```dart
 void doneEditing() async {
    if (_stateManager.editPosition <= 0 && activeLayers.isEmpty) {
      final allowCompleteWithEmptyEditing = widget.allowCompleteWithEmptyEditing;
      if (!allowCompleteWithEmptyEditing) {
        return closeEditor();
      }
    }
    _doneEditing = true;
    LoadingDialog loading = LoadingDialog()
      ..show(
        context,
        i18n: configs.i18n,
        theme: _theme,
        designMode: configs.designMode,
        message: configs.i18n.doneLoadingMsg,
        imageEditorTheme: configs.imageEditorTheme,
      );

    Uint8List bytes = Uint8List.fromList([]);
    try {
      bytes = await _controllers.screenshot.capture(
            pixelRatio: configs.removeTransparentAreas ? null : _pixelRatio,
          ) ??
          bytes;
    } catch (_) {}

    if (configs.removeTransparentAreas) {
      bytes = removeTransparentImgAreas(bytes) ?? bytes;
    }

    // await to complete your code after finish capture the image
    await widget.onImageEditingComplete(bytes);

    // close the loading alert
    if (mounted) loading.hide(context);

    // call that the editor will close now
    widget.onCloseEditor?.call();
  }
```

**Comment by Mohammad2464** [comment]
just check my code and tell me where i was wrong.
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:photo_editing/home_controller.dart';
import 'package:photo_editing/widgets/button.dart';
import 'package:pro_image_editor/pro_image_editor_main.dart';

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final controller = Get.put(HomeController());

  // Method to show dialog when closing the editor
  void _showCloseEditorDialog() {
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return AlertDialog(
          title: Text("Close Editor"),
          content: Text("Are you sure you want to close the editor?"),
          actions: [
            TextButton(
              onPressed: () {
                Navigator.pop(context); // Close the dialog
              },
              child: Text("Cancel"),
            ),
            TextButton(
              onPressed: () {
                Navigator.pop(context); // Close the dialog
                controller.clearImage(); // Clear image when the editor is
closed
              },
              child: Text("Ok"),
            ),
          ],
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Obx(() {
      // Conditionally build Scaffold based on whether an image is selected
or not
      if (controller.isImageSelected.value) {
        return Scaffold(
          body: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Expanded(
                child: Theme(
                  data: ThemeData(
                    appBarTheme: AppBarTheme(
                      color: Colors.blue, // Customize the app bar color
                    ),
                    bottomAppBarTheme: BottomAppBarTheme(
                      color: Colors.blue, // Customize the tab bar color
                    ),
                  ),
                  child: ProImageEditor.file(
                    File(controller.imageFile.value.path),
                    onImageEditingComplete: (editedImage) async {
                      controller.saveImage(context, editedImage);
                    },
                    onCloseEditor: () {
                     _showCloseEditorDialog();// Show dialog when closing
the editor
                    },
                    allowCompleteWithEmptyEditing: true,
                  ),
                ),
              ),
            ],
          ),
        );
      } else {
        return Scaffold(
          appBar: AppBar(
            title: Text(
              "Photo App",
              style: TextStyle(color: Colors.white),
            ),
            centerTitle: true,
            backgroundColor: Colors.blue,
            leading: IconButton(
              onPressed: () {
                controller.clearImage();
              },
              icon: Icon(Icons.home_outlined),
            ),
          ),
          body: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Expanded(
                child: Stack(
                  children: [
                    controller.imageFile.value.path.isEmpty
                        ? Padding(
                            padding:
                                const EdgeInsets.only(top: 300, bottom: 70),
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.
spaceBetween,
                              children: [
                                Text("No image selected"),
                                SizedBox(height: 30),
                                Row(
                                  mainAxisAlignment: MainAxisAlignment.
center,
                                  children: [
                                    PhotoButton(
                                      text: "Take Image",
                                      onPressed: () {
                                        controller
                                            .pickImage(ImageSource.camera);
                                      },
                                      icon: Icons.camera,
                                      color: Colors.blue,
                                    ),
                                    SizedBox(width: 10),
                                    PhotoButton(
                                      text: "Select from Gallery",
                                      onPressed: () {
                                        controller
                                            .pickImage(ImageSource.gallery);
                                      },
                                      icon: Icons.collections,
                                      color: Colors.green,
                                    ),
                                  ],
                                ),
                              ],
                            ),
                          )
                        : SizedBox(),
                  ],
                ),
              ),
            ],
          ),
        );
      }
    });
  }
}

**Comment by hm21** [comment]
In the `onCloseEditor` callback, you don't need to show a dialog anymore because the image editor will do that automatically in case the user changed something on the image. What you should do there is to handle the next step in your app like showing the final image to the user or removing the selected image in the controller so that the user can select another image.
In case you always want to show a close alert even if the user hasn't made any changes, you can easily override the existing appBar with your own solution. The example of how to customize an appBar can be found [here](https://github.com/hm21/pro_image_editor?tab=readme-ov-file#custom-appbar).

**Comment by Mohammad2464** [comment]
Yeah, it works when the user makes some changes but what can i do on
onclose editor callback and oneditingdone callback when the user doesn't do
anything? And app show me black screen when I pressed on oneditorclosed
callback when no changes occured..

**Comment by hm21** [comment]
What do you mean by “when the user doesn't do anything”? Why should the user do nothing? In my opinion, he will in any case close the editor or press done which will also close the editor. 
When you see a black screen, it means that in your code you call Navigator.pop(context) or something with the same behavior, which will close all app pages.

**Comment by Mohammad2464** [comment]
ok but check paint options line width is not scrolling

**Comment by hm21** [comment]
Are you using the latest version `2.6.7`?
